### ISSUE TITLE
arch update: Failed when using register and with_items

### ISSUE THREAD

**Issue by DanSman** [mkapra/ansible-roles#19]
I'm planning to use this:
```
- name: Arch Linux FULL Update via AUR-Helper
  become: true
  shell: "{{ item.AUR_helper }} -Syu --noconfirm --noedit"
  register: output
  with_items:
    - "{{ arch_update }}"
```
Instead of:
```
- name: Arch Linux FULL Update via AUR-Helper
  become: true
  shell: pikaur -Syu --noconfirm --noedit
  register: output
```
To have the possibility to choose the aur helper.   

The problem seems to me that `register` and `with_item` are getting some trouble. 

Here the error message:
```
fatal: [server]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to be in 'roles/update/tasks/main.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Show output\n  ^ here\n"}
```

I have already tried many things. But I can't figure it out. Maybe you have an idea?!
